import { Router, type Response } from "express";
import { requireAuth, type AuthRequest } from "../middleware/auth.js";
import {
  isS3Configured,
  listFiles,
  generatePresignedUrl,
  generatePresignedUploadUrl,
  deleteFile,
  getFileMetadata,
  EXPIRY_PRESETS,
} from "../lib/s3.js";

const router = Router();

router.use(requireAuth);

/**
 * Middleware: check S3 is configured before any storage operation.
 */
router.use((_req: AuthRequest, res: Response, next) => {
  if (!isS3Configured()) {
    res.status(503).json({ error: "Object Storage ist nicht konfiguriert." });
    return;
  }
  next();
});

// GET /storage/files — list files in the bucket
router.get("/files", async (req: AuthRequest, res: Response) => {
  try {
    const prefix = typeof req.query.prefix === "string" ? req.query.prefix : undefined;
    const maxKeys = typeof req.query.limit === "string" ? Math.min(parseInt(req.query.limit, 10), 1000) : 100;
    const continuationToken = typeof req.query.cursor === "string" ? req.query.cursor : undefined;

    const result = await listFiles(prefix, maxKeys, continuationToken);

    res.json(result);
  } catch (err) {
    console.error("[storage] List files error:", err);
    res.status(500).json({ error: "Fehler beim Auflisten der Dateien." });
  }
});

// GET /storage/files/:key/url — generate presigned download URL
// Key is URL-encoded (e.g. "abc123%2Fabc123.mkv" for "abc123/abc123.mkv")
router.get("/files/:key/url", async (req: AuthRequest, res: Response) => {
  try {
    const key = decodeURIComponent(String(req.params.key));
    const expiresParam = typeof req.query.expires === "string" ? req.query.expires : "7d";

    // Resolve expiry: either a preset name or raw seconds
    let expiresIn: number;
    if (expiresParam in EXPIRY_PRESETS) {
      expiresIn = EXPIRY_PRESETS[expiresParam];
    } else {
      expiresIn = parseInt(expiresParam, 10);
      if (isNaN(expiresIn) || expiresIn < 60) {
        res.status(400).json({ error: "Ungültiger expires-Wert. Verwende 1h, 1d, 3d, 7d oder Sekunden (min 60)." });
        return;
      }
    }

    // Verify file exists before generating URL
    try {
      await getFileMetadata(key);
    } catch (err: any) {
      if (err.name === "NotFound" || err.$metadata?.httpStatusCode === 404) {
        res.status(404).json({ error: "Datei nicht gefunden." });
        return;
      }
      throw err;
    }

    const url = await generatePresignedUrl(key, expiresIn);

    const expiresAt = new Date(Date.now() + expiresIn * 1000).toISOString();

    res.json({
      url,
      key,
      expiresIn,
      expiresAt,
    });
  } catch (err) {
    console.error("[storage] Generate URL error:", err);
    res.status(500).json({ error: "Fehler beim Erstellen des Download-Links." });
  }
});

// GET /storage/files/:key/meta — get file metadata
router.get("/files/:key/meta", async (req: AuthRequest, res: Response) => {
  try {
    const key = decodeURIComponent(String(req.params.key));
    const meta = await getFileMetadata(key);

    res.json(meta);
  } catch (err: any) {
    if (err.name === "NotFound" || err.$metadata?.httpStatusCode === 404) {
      res.status(404).json({ error: "Datei nicht gefunden." });
      return;
    }
    console.error("[storage] Get metadata error:", err);
    res.status(500).json({ error: "Fehler beim Abrufen der Metadaten." });
  }
});

// DELETE /storage/files/:key — delete a file
router.delete("/files/:key", async (req: AuthRequest, res: Response) => {
  try {
    const key = decodeURIComponent(String(req.params.key));

    await deleteFile(key);

    console.log(`[storage] Deleted by user ${req.user?.userId}: ${key}`);

    res.json({ success: true, key });
  } catch (err) {
    console.error("[storage] Delete error:", err);
    res.status(500).json({ error: "Fehler beim Löschen der Datei." });
  }
});

// POST /storage/upload-url — generate presigned upload URL
router.post("/upload-url", async (req: AuthRequest, res: Response) => {
  try {
    const { key, contentType, expiresIn: rawExpiry } = req.body;

    if (!key || typeof key !== "string") {
      res.status(400).json({ error: "key ist erforderlich (string)." });
      return;
    }

    const expiresIn = typeof rawExpiry === "number" ? Math.min(rawExpiry, 3600) : 3600;

    const url = await generatePresignedUploadUrl(key, contentType, expiresIn);

    const expiresAt = new Date(Date.now() + expiresIn * 1000).toISOString();

    console.log(`[storage] Upload URL generated by user ${req.user?.userId}: ${key}`);

    res.json({
      url,
      key,
      expiresIn,
      expiresAt,
    });
  } catch (err) {
    console.error("[storage] Generate upload URL error:", err);
    res.status(500).json({ error: "Fehler beim Erstellen der Upload-URL." });
  }
});

export default router;
